name: WAF
channels:
  - conda-forge
dependencies:
  - scipy
  - geopandas
  - shapely
  - numpy
  - pandas
  - matplotlib
  - scikit-learn>=0.20
  - jupyter
  - googledrivedownloader
  - pip:
      - https://api.github.com/repos/paris-saclay-cds/ramp-workflow/zipball/master